chain:
    bech32_prefix: vcg
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - slashing
        - staking
        - distribution
        - actions
        - vipcoin

node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://localhost:26657
            max_connections: 10
        grpc:
            address: http://localhost:9090
            insecure: true
parsing:
    workers: 10
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: false
    start_height: 1
    genesis_file_path: ./volume/genesis.json
    average_block_time: 3s
database:
    name: juno
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    enabled: false

actions:
    port: 3000
    node: 
        rpc:
            address: http://localhost:26657 
        grpc:
            address: http://localhost:9090
            insecure: true
